import {
  type CentralizedCalculator,
  type LocalizedCalculatorCategory,
  toCalculator,
} from "@/lib/calculator-model";

export const germanCalculatorCategories: LocalizedCalculatorCategory[] = [
  { id: "de-work-salary", locale: "de", slug: "arbeit-lohn", title: "Arbeit & Lohn", description: "Arbeitszeit, Stunden und Schweizer Lohn verständlich berechnen." },
  { id: "de-tax-vat", locale: "de", slug: "steuern-mehrwertsteuer", title: "Steuern & Mehrwertsteuer", description: "Steuer- und MWST-Beträge schnell nachvollziehen." },
  { id: "de-finance", locale: "de", slug: "finanzen", title: "Finanzen", description: "Kapital, Rendite und persönliche Finanzziele planen." },
  { id: "de-credit-interest", locale: "de", slug: "kredit-zinsen", title: "Kredit & Zinsen", description: "Raten, Zinskosten und Laufzeiten vergleichen." },
  { id: "de-household-budget", locale: "de", slug: "haushalt-budget", title: "Haushalt & Budget", description: "Einnahmen und laufende Ausgaben übersichtlich planen." },
  { id: "de-car-mobility", locale: "de", slug: "auto-mobilitaet", title: "Auto & Mobilität", description: "Kosten rund um Auto und Mobilität einschätzen." },
  { id: "de-health", locale: "de", slug: "gesundheit", title: "Gesundheit", description: "Gesundheits- und Versicherungskosten vergleichen." },
  { id: "de-time-date", locale: "de", slug: "zeit-datum", title: "Zeit & Datum", description: "Arbeitsstunden, Ferien und Zeiträume berechnen." },
];

export const germanPriorityCalculatorData: CentralizedCalculator[] = [
  {
    id: "de-hours",
    locale: "de",
    slug: "stundenrechner",
    kind: "work-hours",
    category: "Zeit & Datum",
    title: "Stundenrechner: Arbeitsstunden und Pausen berechnen | Calcolich",
    metaDescription: "Arbeitsstunden kostenlos berechnen: Start, Ende und Pause eingeben und Nettozeit sofort als Stunden und Minuten erhalten.",
    h1: "Stundenrechner",
    shortTitle: "Stundenrechner",
    intro: "Berechne die Zeit zwischen Arbeitsbeginn und Feierabend. Pausen werden automatisch von der Anwesenheitszeit abgezogen.",
    formula: "Die Nettoarbeitszeit ergibt sich aus Endzeit minus Startzeit minus Pause. Endet eine Schicht nach Mitternacht, wird der Tageswechsel automatisch berücksichtigt.",
    example: "Beispiel: Von 08:00 bis 17:30 liegen 9 Stunden 30 Minuten. Nach Abzug einer Pause von 60 Minuten bleiben 8 Stunden 30 Minuten Nettoarbeitszeit.",
    supportingContent: ["Der Rechner eignet sich für einzelne Arbeitstage, Schichten und die schnelle Kontrolle eines Stundenzettels. Vertragliche Rundungsregeln werden nicht berücksichtigt."],
    faqs: [
      { question: "Kann der Stundenrechner Pausen abziehen?", answer: "Ja. Trage die gesamte unbezahlte Pause in Minuten ein; sie wird von der Zeitspanne abgezogen." },
      { question: "Funktioniert der Rechner über Mitternacht?", answer: "Ja. Liegt die Endzeit vor der Startzeit, behandelt der Rechner das Ende als Zeitpunkt am Folgetag." },
      { question: "Sind Dezimalstunden und Stunden:Minuten gleich?", answer: "Sie beschreiben dieselbe Dauer. 8 Stunden 30 Minuten entsprechen 8,5 Dezimalstunden." },
    ],
    relatedCalculators: ["arbeitszeitrechner", "lohnrechner-schweiz", "ferienrechner-schweiz"],
    monetizationType: "mixed",
    schemaType: "WebApplication",
    isPriority: true,
    searchIntent: "Arbeitsstunden zwischen zwei Uhrzeiten inklusive Pause berechnen",
    inputs: [
      { key: "start", label: "Arbeitsbeginn", type: "time", defaultValue: "08:00" },
      { key: "end", label: "Arbeitsende", type: "time", defaultValue: "17:30" },
      { key: "breakMinutes", label: "Pause in Minuten", defaultValue: "60", min: "0", max: "1440" },
    ],
    resultLabels: ["Netto-Minuten", "Dezimalstunden", "Arbeitszeit"],
    cta: "Neue Rechner für Arbeitszeit, Lohn und Ferien direkt per E-Mail erhalten.",
  },
  {
    id: "de-working-time",
    locale: "de",
    slug: "arbeitszeitrechner",
    kind: "working-time",
    category: "Arbeit & Lohn",
    title: "Arbeitszeitrechner: tägliche und wöchentliche Arbeitszeit | Calcolich",
    metaDescription: "Tägliche, wöchentliche und monatliche Arbeitszeit berechnen. Beginn, Ende, Pause und Arbeitstage einfach eingeben.",
    h1: "Arbeitszeitrechner",
    shortTitle: "Arbeitszeit",
    intro: "Ermittle deine Nettoarbeitszeit pro Tag und rechne sie auf Woche und durchschnittlichen Monat hoch.",
    formula: "Zuerst wird die tägliche Nettozeit aus Arbeitsende minus Arbeitsbeginn minus Pause berechnet. Die Wochenzeit entspricht der Tageszeit mal Arbeitstage; für den Monatswert wird mit 52/12 Wochen gerechnet.",
    example: "Beispiel: 8 Stunden 24 Minuten netto an fünf Tagen ergeben 42 Wochenstunden und durchschnittlich rund 182 Monatsstunden.",
    supportingContent: ["Der Monatswert ist ein rechnerischer Durchschnitt. Feiertage, Ferien, Krankheit und abweichende Schichten verändern die tatsächlich geleisteten Stunden."],
    faqs: [
      { question: "Wie werden Monatsstunden berechnet?", answer: "Die Wochenstunden werden mit 52 multipliziert und durch 12 geteilt. Dadurch entsteht ein durchschnittlicher Monatswert." },
      { question: "Zählt die Pause zur Arbeitszeit?", answer: "Nur bezahlte Pausen zählen üblicherweise als Arbeitszeit. Hier wird die eingegebene Pause vollständig abgezogen." },
      { question: "Kann ich Teilzeit berechnen?", answer: "Ja. Wähle einfach die tatsächliche Anzahl Arbeitstage und deine täglichen Zeiten." },
    ],
    relatedCalculators: ["stundenrechner", "lohnrechner-schweiz", "ferienrechner-schweiz"],
    monetizationType: "lead",
    schemaType: "WebApplication",
    isPriority: true,
    searchIntent: "Arbeitszeit pro Tag, Woche und Monat ausrechnen",
    inputs: [
      { key: "start", label: "Arbeitsbeginn", type: "time", defaultValue: "08:00" },
      { key: "end", label: "Arbeitsende", type: "time", defaultValue: "17:24" },
      { key: "breakMinutes", label: "Pause pro Tag in Minuten", defaultValue: "60", min: "0" },
      { key: "daysPerWeek", label: "Arbeitstage pro Woche", defaultValue: "5", step: "0.5", min: "1", max: "7" },
    ],
    resultLabels: ["Pro Tag", "Pro Woche", "Pro Monat"],
    cta: "Praktische Vorlagen und neue Arbeitsrechner per E-Mail erhalten.",
  },
  {
    id: "de-salary-ch",
    locale: "de",
    slug: "lohnrechner-schweiz",
    kind: "salary-net-ch",
    category: "Arbeit & Lohn",
    title: "Lohnrechner Schweiz 2026: Nettolohn schätzen | Calcolich",
    metaDescription: "Schweizer Nettolohn aus dem Bruttolohn schätzen. AHV, ALV, Unfallversicherung, Pensionskasse und weitere Abzüge anpassen.",
    h1: "Lohnrechner Schweiz",
    shortTitle: "Lohnrechner Schweiz",
    intro: "Schätze deinen monatlichen Nettolohn aus dem Bruttolohn und individuell einstellbaren Abzügen.",
    formula: "Alle eingegebenen Abzugssätze werden addiert und auf den Bruttolohn angewendet. Nettolohn = Bruttolohn minus geschätzte Abzüge.",
    example: "Beispiel: Bei CHF 6'500 Bruttolohn und insgesamt 14,6 Prozent Abzügen werden CHF 949 abgezogen. Der geschätzte Nettolohn beträgt CHF 5'551.",
    supportingContent: ["Der tatsächliche Nettolohn hängt unter anderem von Alter, Pensionskasse, Unfallversicherung, Kanton und Quellensteuer ab. Nutze Werte aus deiner Lohnabrechnung für eine bessere Schätzung."],
    faqs: [
      { question: "Ist die Quellensteuer enthalten?", answer: "Du kannst sie zusammen mit weiteren individuellen Abzügen im letzten Feld eintragen." },
      { question: "Warum ist der Nettolohn nur eine Schätzung?", answer: "Pensionskasse, Versicherungen und Steuern unterscheiden sich nach Person, Arbeitgeber und Kanton." },
      { question: "Kann ich einen Jahreslohn eingeben?", answer: "Dieser Rechner arbeitet mit Monatslohn. Teile den Jahreslohn je nach Vertrag durch zwölf oder dreizehn Monatslöhne." },
    ],
    relatedCalculators: ["brutto-netto-rechner-schweiz", "arbeitszeitrechner", "budget-rechner-schweiz"],
    monetizationType: "mixed",
    schemaType: "WebApplication",
    isPriority: true,
    searchIntent: "Nettolohn in der Schweiz aus Bruttolohn berechnen",
    inputs: [
      { key: "gross", label: "Bruttolohn pro Monat (CHF)", defaultValue: "6500", min: "0" },
      { key: "avs", label: "AHV/IV/EO (%)", defaultValue: "5.3", step: "0.1", min: "0" },
      { key: "alv", label: "ALV (%)", defaultValue: "1.1", step: "0.1", min: "0" },
      { key: "accident", label: "Nichtberufsunfall (%)", defaultValue: "1.2", step: "0.1", min: "0" },
      { key: "pension", label: "Pensionskasse (%)", defaultValue: "7", step: "0.1", min: "0" },
      { key: "other", label: "Weitere Abzüge / Quellensteuer (%)", defaultValue: "0", step: "0.1", min: "0" },
    ],
    resultLabels: ["Abzugssatz", "Abzüge", "Nettolohn geschätzt"],
    cta: "Neue Schweizer Lohn- und Steuerrechner per E-Mail erhalten.",
  },
  {
    id: "de-gross-net-ch",
    locale: "de",
    slug: "brutto-netto-rechner-schweiz",
    kind: "gross-net-ch",
    category: "Arbeit & Lohn",
    title: "Brutto-Netto-Rechner Schweiz: Lohn umrechnen | Calcolich",
    metaDescription: "Brutto in Netto oder gewünschten Nettolohn in erforderlichen Bruttolohn umrechnen. Kostenloser Rechner für die Schweiz.",
    h1: "Brutto-Netto-Rechner Schweiz",
    shortTitle: "Brutto-Netto",
    intro: "Rechne einen Schweizer Bruttolohn in einen geschätzten Nettolohn um oder ermittle den nötigen Bruttolohn für dein Nettoziel.",
    formula: "Bei Brutto zu Netto wird der Abzugssatz vom Bruttolohn abgezogen. Bei Netto zu Brutto wird der Nettobetrag durch 1 minus Abzugssatz geteilt.",
    example: "Beispiel: CHF 7'000 brutto bei 15 Prozent Abzügen ergeben CHF 5'950 netto. Für CHF 6'000 netto wären bei gleichem Satz rund CHF 7'058.82 brutto nötig.",
    supportingContent: ["Der pauschale Abzugssatz vereinfacht die Rechnung. Für eine detailliertere Schätzung kannst du den Schweizer Lohnrechner mit einzelnen Abzugspositionen verwenden."],
    faqs: [
      { question: "Welchen Abzugssatz soll ich verwenden?", answer: "Am besten übernimmst du den Gesamtanteil aus einer aktuellen Lohnabrechnung. Ohne Referenz ist der Wert nur eine Annahme." },
      { question: "Sind Steuern im Ergebnis enthalten?", answer: "Nur wenn du sie in den pauschalen Abzugssatz einrechnest. Ordentlich veranlagte Einkommenssteuern stehen meist nicht auf der Lohnabrechnung." },
      { question: "Funktioniert die Rückrechnung von Netto zu Brutto?", answer: "Ja. Wähle den entsprechenden Modus und gib Nettobetrag sowie geschätzten Abzugssatz ein." },
    ],
    relatedCalculators: ["lohnrechner-schweiz", "stundenrechner", "budget-rechner-schweiz"],
    monetizationType: "mixed",
    schemaType: "WebApplication",
    isPriority: true,
    searchIntent: "Schweizer Lohn zwischen brutto und netto umrechnen",
    inputs: [
      { key: "mode", label: "Berechnung", type: "select", defaultValue: "gross-to-net", options: [{ label: "Brutto zu Netto", value: "gross-to-net" }, { label: "Netto zu Brutto", value: "net-to-gross" }] },
      { key: "amount", label: "Betrag (CHF)", defaultValue: "7000", min: "0" },
      { key: "deductionRate", label: "Geschätzte Gesamtabzüge (%)", defaultValue: "15", step: "0.1", min: "0", max: "80" },
    ],
    resultLabels: ["Geschätzte Abzüge", "Bruttolohn", "Nettolohn"],
    cta: "Lohnrechner und Checklisten für die Schweiz per E-Mail erhalten.",
  },
  {
    id: "de-vat-ch",
    locale: "de",
    slug: "mehrwertsteuer-rechner-schweiz",
    kind: "vat-ch",
    category: "Steuern & Mehrwertsteuer",
    title: "Mehrwertsteuer-Rechner Schweiz 2026: MWST berechnen | Calcolich",
    metaDescription: "Schweizer MWST aufschlagen oder aus einem Bruttobetrag herausrechnen. Mit frei wählbarem Mehrwertsteuersatz.",
    h1: "Mehrwertsteuer-Rechner Schweiz",
    shortTitle: "MWST-Rechner",
    intro: "Berechne Nettobetrag, Mehrwertsteuer und Bruttobetrag für Schweizer Rechnungen und Preise.",
    formula: "Beim Aufschlagen gilt: MWST = Nettobetrag × Steuersatz. Beim Herausrechnen gilt: Nettobetrag = Bruttobetrag ÷ (1 + Steuersatz).",
    example: "Beispiel: CHF 1'000 netto zu 8,1 Prozent ergeben CHF 81 MWST und CHF 1'081 brutto. Aus CHF 1'081 brutto werden wieder CHF 1'000 netto herausgerechnet.",
    supportingContent: ["Prüfe vor der Rechnung, welcher Steuersatz für deine Leistung gilt. Der Rechner erstellt keine steuerliche Beurteilung und ersetzt keine Buchhaltungssoftware."],
    faqs: [
      { question: "Kann ich die MWST aus einem Bruttobetrag herausrechnen?", answer: "Ja. Wähle den Modus 'MWST herausrechnen' und gib den Gesamtbetrag ein." },
      { question: "Kann ich einen reduzierten Satz verwenden?", answer: "Ja. Der Prozentsatz ist frei editierbar, damit du den für deine Leistung geltenden Satz eintragen kannst." },
      { question: "Warum ist Herausrechnen nicht einfach Betrag mal Prozentsatz?", answer: "Weil der Bruttobetrag die Steuer bereits enthält. Deshalb wird durch 1 plus Steuersatz geteilt." },
    ],
    relatedCalculators: ["prozentrechner", "zinsrechner", "budget-rechner-schweiz"],
    monetizationType: "affiliate",
    schemaType: "WebApplication",
    isPriority: true,
    searchIntent: "Schweizer Mehrwertsteuer aufschlagen oder herausrechnen",
    inputs: [
      { key: "mode", label: "Berechnung", type: "select", defaultValue: "add", options: [{ label: "MWST aufschlagen", value: "add" }, { label: "MWST herausrechnen", value: "remove" }] },
      { key: "amount", label: "Betrag (CHF)", defaultValue: "1000", min: "0" },
      { key: "rate", label: "MWST-Satz (%)", defaultValue: "8.1", step: "0.1", min: "0", max: "100" },
    ],
    resultLabels: ["Nettobetrag", "Mehrwertsteuer", "Bruttobetrag"],
    cta: "Neue Rechner für MWST, Preise und Selbstständige per E-Mail erhalten.",
  },
  {
    id: "de-percentage",
    locale: "de",
    slug: "prozentrechner",
    kind: "percentage",
    category: "Finanzen",
    title: "Prozentrechner: Prozentwert einfach online berechnen | Calcolich",
    metaDescription: "Berechne schnell, wie viel ein Prozentsatz von einem Grundwert ist. Kostenloser Prozentrechner mit Formel und Beispiel.",
    h1: "Prozentrechner",
    shortTitle: "Prozentrechner",
    intro: "Finde heraus, wie viel ein bestimmter Prozentsatz von einem Wert ausmacht.",
    formula: "Prozentwert = Grundwert × Prozentsatz ÷ 100. Der Grundwert entspricht dabei immer 100 Prozent.",
    example: "Beispiel: 18 Prozent von CHF 2'500 sind CHF 450, denn 2'500 × 18 ÷ 100 = 450.",
    supportingContent: ["Der Rechner eignet sich für Rabatte, Budgetanteile, Gebühren, Provisionen und viele alltägliche Prozentfragen."],
    faqs: [
      { question: "Wie berechnet man einen Prozentsatz von einem Betrag?", answer: "Multipliziere den Betrag mit dem Prozentsatz und teile das Ergebnis durch 100." },
      { question: "Was ist der Grundwert?", answer: "Der Grundwert ist der vollständige Ausgangswert und entspricht 100 Prozent." },
      { question: "Kann ich Dezimalwerte eingeben?", answer: "Ja. Sowohl Grundwert als auch Prozentsatz dürfen Dezimalstellen enthalten." },
    ],
    relatedCalculators: ["mehrwertsteuer-rechner-schweiz", "zinsrechner", "kreditrechner"],
    monetizationType: "adsense",
    schemaType: "WebApplication",
    isPriority: true,
    searchIntent: "Prozentwert eines Grundwerts berechnen",
    inputs: [
      { key: "base", label: "Grundwert", defaultValue: "2500", step: "0.01" },
      { key: "rate", label: "Prozentsatz (%)", defaultValue: "18", step: "0.01" },
    ],
    resultLabels: ["Grundwert", "Prozentsatz", "Prozentwert"],
    cta: "Neue Alltags- und Finanzrechner kostenlos per E-Mail erhalten.",
  },
  {
    id: "de-interest",
    locale: "de",
    slug: "zinsrechner",
    kind: "compound-interest",
    category: "Kredit & Zinsen",
    title: "Zinsrechner: Zinseszins und Sparplan berechnen | Calcolich",
    metaDescription: "Zinseszins mit Startkapital, monatlicher Einzahlung, Zinssatz und Laufzeit berechnen. Kostenloser Online-Zinsrechner.",
    h1: "Zinsrechner",
    shortTitle: "Zinsrechner",
    intro: "Berechne, wie sich Startkapital und monatliche Einzahlungen bei einem konstanten Jahreszins entwickeln können.",
    formula: "Der Rechner verzinst das vorhandene Kapital monatlich und addiert danach die Monatsrate. Der jährliche Zinssatz wird dafür durch zwölf geteilt.",
    example: "Beispiel: CHF 10'000 Startkapital plus CHF 300 monatlich wachsen bei 3 Prozent über zehn Jahre auf einen höheren Endwert als die Summe aller Einzahlungen, weil Erträge wieder mitverzinst werden.",
    supportingContent: ["Die Rechnung ist eine Modellannahme mit konstantem Zinssatz. Gebühren, Steuern, Kursschwankungen und wechselnde Renditen sind nicht enthalten."],
    faqs: [
      { question: "Was bedeutet Zinseszins?", answer: "Erträge werden dem Kapital zugerechnet und in den folgenden Perioden ebenfalls verzinst." },
      { question: "Sind Gebühren und Steuern enthalten?", answer: "Nein. Der Rechner zeigt eine vereinfachte Bruttoentwicklung ohne Kosten und Steuern." },
      { question: "Ist der angezeigte Endwert garantiert?", answer: "Nein. Er ist eine mathematische Simulation mit konstantem Zinssatz, keine Renditegarantie." },
    ],
    relatedCalculators: ["kreditrechner", "prozentrechner", "budget-rechner-schweiz"],
    monetizationType: "affiliate",
    schemaType: "WebApplication",
    isPriority: true,
    searchIntent: "Zinseszins und Sparplan mit monatlicher Einzahlung berechnen",
    inputs: [
      { key: "initial", label: "Startkapital (CHF)", defaultValue: "10000", min: "0" },
      { key: "monthly", label: "Monatliche Einzahlung (CHF)", defaultValue: "300", min: "0" },
      { key: "rate", label: "Jahreszins (%)", defaultValue: "3", step: "0.1" },
      { key: "years", label: "Laufzeit in Jahren", defaultValue: "10", min: "1", max: "80" },
    ],
    resultLabels: ["Einzahlungen", "Zinsertrag geschätzt", "Endkapital"],
    cta: "Neue Spar- und Finanzrechner sowie Vorlagen per E-Mail erhalten.",
  },
  {
    id: "de-loan",
    locale: "de",
    slug: "kreditrechner",
    kind: "loan-payment",
    category: "Kredit & Zinsen",
    title: "Kreditrechner: Rate und Zinskosten online berechnen | Calcolich",
    metaDescription: "Monatliche Kreditrate, Gesamtzahlung und Zinskosten aus Kreditsumme, Laufzeit und Jahreszins berechnen.",
    h1: "Kreditrechner",
    shortTitle: "Kreditrechner",
    intro: "Berechne die konstante Monatsrate eines Kredits und vergleiche Gesamtzahlung und Zinskosten.",
    formula: "Bei einem Annuitätendarlehen wird die Monatsrate aus Kreditsumme, monatlichem Zinssatz und Anzahl Raten berechnet. Bei null Prozent wird die Summe gleichmässig aufgeteilt.",
    example: "Beispiel: Ein Kredit über CHF 25'000 mit 5,9 Prozent Jahreszins und 48 Monaten erzeugt eine feste Monatsrate; die Differenz zwischen allen Raten und CHF 25'000 sind die Zinskosten.",
    supportingContent: ["Anbieter können zusätzlich Gebühren, Versicherungen oder abweichende Berechnungsmethoden verwenden. Vergleiche deshalb immer den effektiven Jahreszins und das verbindliche Angebot."],
    faqs: [
      { question: "Was zeigt die Monatsrate?", answer: "Sie zeigt die rechnerisch konstante Rate aus Tilgung und Zins für die gewählte Laufzeit." },
      { question: "Was passiert bei längerer Laufzeit?", answer: "Die Monatsrate sinkt meist, während die gesamten Zinskosten in der Regel steigen." },
      { question: "Sind Kreditgebühren enthalten?", answer: "Nein. Der Rechner berücksichtigt nur Kreditsumme, Laufzeit und eingegebenen Zinssatz." },
    ],
    relatedCalculators: ["zinsrechner", "prozentrechner", "budget-rechner-schweiz"],
    monetizationType: "affiliate",
    schemaType: "WebApplication",
    isPriority: true,
    searchIntent: "Kreditrate und gesamte Zinskosten berechnen",
    inputs: [
      { key: "principal", label: "Kreditsumme (CHF)", defaultValue: "25000", min: "0" },
      { key: "months", label: "Laufzeit in Monaten", defaultValue: "48", min: "1", max: "360" },
      { key: "rate", label: "Jahreszins (%)", defaultValue: "5.9", step: "0.1", min: "0" },
    ],
    resultLabels: ["Monatsrate", "Gesamtzahlung", "Zinskosten"],
    cta: "Checklisten für Budget und Finanzentscheidungen per E-Mail erhalten.",
  },
  {
    id: "de-budget-ch",
    locale: "de",
    slug: "budget-rechner-schweiz",
    kind: "monthly-budget-ch",
    category: "Haushalt & Budget",
    title: "Budget-Rechner Schweiz: Monatsbudget einfach planen | Calcolich",
    metaDescription: "Monatliches Haushaltsbudget für die Schweiz berechnen. Einkommen, Wohnen, Krankenkasse und weitere Ausgaben übersichtlich vergleichen.",
    h1: "Budget-Rechner Schweiz",
    shortTitle: "Budget-Rechner",
    intro: "Stelle dein monatliches Einkommen den wichtigsten Fixkosten gegenüber und ermittle freien Betrag und Sparquote.",
    formula: "Gesamtausgaben = Wohnen + Krankenkasse + weitere Ausgaben. Der Saldo ist Einkommen minus Gesamtausgaben; die Sparquote entspricht Saldo geteilt durch Einkommen mal 100.",
    example: "Beispiel: Bei CHF 5'500 Einkommen und CHF 4'200 Gesamtausgaben bleiben CHF 1'300. Das entspricht einer rechnerischen Sparquote von rund 23,64 Prozent.",
    supportingContent: ["Nutze bei den weiteren Ausgaben möglichst einen realistischen Monatsdurchschnitt für Lebensmittel, Mobilität, Versicherungen, Freizeit und unregelmässige Jahresrechnungen."],
    faqs: [
      { question: "Welche Ausgaben gehören ins Monatsbudget?", answer: "Neben Wohnen und Krankenkasse gehören auch Lebensmittel, Mobilität, Versicherungen, Steuern, Freizeit und Rückstellungen dazu." },
      { question: "Was bedeutet eine negative Sparquote?", answer: "Dann liegen die eingegebenen Ausgaben über dem Einkommen. Das Budget weist ein monatliches Defizit aus." },
      { question: "Wie berücksichtige ich Jahresrechnungen?", answer: "Teile erwartete Jahreskosten durch zwölf und addiere den Betrag zu den weiteren monatlichen Ausgaben." },
    ],
    relatedCalculators: ["lohnrechner-schweiz", "kreditrechner", "zinsrechner"],
    monetizationType: "lead",
    schemaType: "WebApplication",
    isPriority: true,
    searchIntent: "Monatliches Haushaltsbudget in der Schweiz berechnen",
    inputs: [
      { key: "income", label: "Nettoeinkommen pro Monat (CHF)", defaultValue: "5500", min: "0" },
      { key: "rent", label: "Miete und Wohnen (CHF)", defaultValue: "1800", min: "0" },
      { key: "healthInsurance", label: "Krankenkasse (CHF)", defaultValue: "450", min: "0" },
      { key: "otherCosts", label: "Weitere Ausgaben (CHF)", defaultValue: "1950", min: "0" },
    ],
    resultLabels: ["Gesamtausgaben", "Sparquote", "Monatlicher Saldo"],
    cta: "Die kommende Budgetvorlage und neue Schweizer Rechner per E-Mail erhalten.",
  },
  {
    id: "de-vacation-ch",
    locale: "de",
    slug: "ferienrechner-schweiz",
    kind: "vacation-ch",
    category: "Zeit & Datum",
    title: "Ferienrechner Schweiz: Ferienanspruch berechnen | Calcolich",
    metaDescription: "Ferientage für die Schweiz aus Arbeitstagen, Ferienwochen und Beschäftigungsmonaten berechnen. Schnell und kostenlos.",
    h1: "Ferienrechner Schweiz",
    shortTitle: "Ferienrechner",
    intro: "Berechne deinen jährlichen Ferienanspruch und den anteiligen Anspruch für eine bestimmte Anzahl Beschäftigungsmonate.",
    formula: "Ferientage pro Jahr = Arbeitstage pro Woche × Ferienwochen. Der anteilige Anspruch entspricht den Jahrestagen × Beschäftigungsmonate ÷ 12.",
    example: "Beispiel: Fünf Arbeitstage und vier Ferienwochen ergeben 20 Ferientage pro Jahr. Nach neun Beschäftigungsmonaten sind rechnerisch 15 Tage entstanden.",
    supportingContent: ["Der Rechner zeigt einen mathematischen Anspruch. Arbeitsvertrag, Eintritts- und Austrittsdatum, unbezahlter Urlaub sowie Rundungsregeln können den offiziellen Saldo beeinflussen."],
    faqs: [
      { question: "Wie viele Ferientage ergeben vier Ferienwochen?", answer: "Bei fünf Arbeitstagen pro Woche sind es 20 Tage; bei vier Arbeitstagen sind es 16 Tage." },
      { question: "Werden angebrochene Monate berücksichtigt?", answer: "Der Rechner arbeitet mit der eingegebenen Anzahl Monate. Für genaue Tagesabrechnungen gelten die Regeln des Arbeitgebers." },
      { question: "Gilt das Ergebnis als offizieller Feriensaldo?", answer: "Nein. Bereits bezogene Ferien, Überträge und vertragliche Regeln müssen zusätzlich berücksichtigt werden." },
    ],
    relatedCalculators: ["stundenrechner", "arbeitszeitrechner", "lohnrechner-schweiz"],
    monetizationType: "lead",
    schemaType: "WebApplication",
    isPriority: true,
    searchIntent: "Ferienanspruch in der Schweiz anteilig berechnen",
    inputs: [
      { key: "daysPerWeek", label: "Arbeitstage pro Woche", defaultValue: "5", step: "0.5", min: "1", max: "7" },
      { key: "weeks", label: "Ferienwochen pro Jahr", defaultValue: "4", step: "0.5", min: "1", max: "10" },
      { key: "months", label: "Beschäftigungsmonate", defaultValue: "12", min: "1", max: "12" },
    ],
    resultLabels: ["Ferientage pro Jahr", "Berücksichtigte Monate", "Anteiliger Anspruch"],
    cta: "Neue Rechner und Vorlagen für Arbeit und Ferien per E-Mail erhalten.",
  },
];

export const germanPriorityCalculators = germanPriorityCalculatorData.map(toCalculator);

export function getGermanPriorityCalculator(slug: string) {
  return germanPriorityCalculators.find((calculator) => calculator.slug === slug);
}
